agentName: vm
agentType: vuln
title: 'Import Dependabot data'
metaDescription: 'Test for vuln mgmt.'
introFilePath: 'src/install/vm/intro.mdx'
agentConfigFilePath: 'src/install/config/agent-config/java-newrelic.yml'
redirects:
  - /docs/vulnerability-management/integrations/dependabot
appInfo:
  - optionType: deployment
    label: 'Do you want to send new or previously detected vulnerabilities?'
    placeholder: 'I want to send...'
    options:
      - value: 'new'
        displayName: 'New vulnerabilities'
      - value: 'previous'
        displayName: 'Previously detected vulnerabilities'

steps:
  - filePath: 'src/install/vm/appInfo.mdx'
  - filePath: 'src/install/vm/deployment/default.mdx'
    overrides:
      - filePath: 'src/install/vm/deployment/new.mdx'
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'new'
      - filePath: 'src/install/vm/deployment/previous.mdx'
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'previous'
whatsNextFilePath: 'src/install/vm/whatsNext.mdx'
